---
# 参考 https://zenn.dev/januswel/articles/402774d76424e71ac906
# 参考 https://dev.classmethod.jp/articles/eslint-configurations-2020/
root: true
env:
  es2020: true
  jest/globals: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json
plugins:
  - "@typescript-eslint"
  - jest
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - prettier
rules:
  "@typescript-eslint/naming-convention":
  - "error"
  # クラス
  - "selector": "class"
    "format":
    - "PascalCase"
    "leadingUnderscore": "forbid"
    "trailingUnderscore": "forbid"
  # メソッド
  - "selector": "method"
    "format":
    - "camelCase"
    "leadingUnderscore": "forbid"
    "trailingUnderscore": "forbid"
  # インターフェース
  - "selector": "interface"
    "format":
    - "PascalCase"
    "leadingUnderscore": "forbid"
    "trailingUnderscore": "forbid"
  # タイプ
  - "selector": "typeAlias"
    "format":
    - "PascalCase"
    "leadingUnderscore": "forbid"
    "trailingUnderscore": "forbid"
  # Enum
  - "selector": "enum"
    "format":
    - "PascalCase"
    "leadingUnderscore": "forbid"
    "trailingUnderscore": "forbid"
  # export const
  - "selector": "variable"
    "types":
    - "function"
    "format":
    - "camelCase"
    "leadingUnderscore": "forbid"
    "trailingUnderscore": "forbid"
